name: codelab_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  qr_code_scanner: ^0.0.12
  openfoodfacts:
    git:
      url: https://github.com/openfoodfacts/openfoodfacts-dart

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
